# Generated by Django 4.2.4 on 2025-11-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('accepted', 'Đã chấp nhận'), ('packed', 'Đã đóng gói'), ('on_the_way', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('online', 'Thanh toán online')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('success', 'Thanh toán thành công'), ('failed', 'Thanh toán thất bại')], default='pending', max_length=100),
        ),
    ]
